anchors:
  - &targetDefaults
    replicaCount: 1
    slowloris:
      enabled: false
      https: true
      extraArgs: -s 5000
      resources: {}
    ddosify:
      enabled: true
      protocol: HTTPS
      extraArgs: -d 3600
      resources:
        limits:
          cpu: 10m
          memory: 10Mi
        requests:
          cpu: 5m
          memory: 8Mi
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80

targets:
  example: # Should be unique key [a-z0-9-]
    <<: *targetDefaults # Default values see before, you can reassign them below
    replicaCount: 20    # Change it for better or less performance
    host: example.com   # Target host
    port: 443           # Target port
